In [3]:
#importing
import numpy as np #we can use numpy as a shorten way 'np'

In [8]:
arr = np.array([1,2,3]) 
print(arr)

[1 2 3]


In [9]:
arr2= np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

print(arr2.shape) 

(15,)


In [11]:
a = arr2.reshape(3,5) 
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [12]:
print("shape: ",a.shape)
print("dimension: ",a.ndim)
print("data type: ",a.dtype.name) 
print("size: ",a.size)
print("type",type(a)) 

shape:  (3, 5)
dimension:  2
data type:  int64
size:  15
type <class 'numpy.ndarray'>


In [13]:
arr3= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

In [14]:
print(arr3) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr3.shape) 

(3, 4)


In [16]:
zeros= np.zeros((3,4))

In [ ]:
zeros[0,0]=5
print(zeros)

[[5. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [20]:
np.arange(10,50,5) 

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
a= np.linspace(0,10,20) 
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [22]:
a= np.array([1,2,3])
b= np.array([4,5,6]) 

print(a+b) 
print(a-b)
print(a**2)

[5 7 9]
[-3 -3 -3]
[1 4 9]


In [23]:
a= np.array([1,2,3,4,5,6,7])

In [24]:
liste = [1,2,3,4]
array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [25]:
array = np.array(liste)
print(array)

[1 2 3 4]


In [26]:
liste2 = list(array) 
print(liste2)

[1, 2, 3, 4]


In [27]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [28]:
b=a
c=a
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [29]:
d = a.copy()

In [30]:
a= np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [31]:
print(a[0])

1


In [32]:
print(a[0:4]) 

[1 2 3 4]


In [33]:
reverse_array = a[::-1] 
print(reverse_array)

[7 6 5 4 3 2 1]


In [34]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]]) 
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [35]:
print(b[1,1]) 
print(b[:,1])
print(b[1,:])
print(b[1,1:4]) 
print(b[-1,:]) 
print(b[:,-1]) 

7
[2 7]
[ 6  7  8  9 10]
[7 8 9]
[ 6  7  8  9 10]
[ 5 10]


In [36]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
a = array.ravel() 
print(a)

[1 2 3 4 5 6 7 8 9]


In [38]:
array2 = a.reshape(3,3) 
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
array_transpose = array2.T
print(array_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
arr3 = np.array([[1,2],[3,4],[5,6]])
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [47]:
arr3.resize((2,3)) 
print(arr3)

[[1 2 3]
 [4 5 6]]
